### ISSUE TITLE
Master issue

### ISSUE THREAD

**Issue by jdubie** [kinesis/fib_py#4]
- [ ] scripts that runs test
- [ ] travis CI run tests inside docker image
- [ ] script that runs benchmark
- [ ] refine source tree
- [ ] benchmarking
- [ ] code that tests both implementations
